/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MedicalRecordAudit } from "./MedicalRecordAudit";
export * as factories from "./factories";
export { MedicalRecordAudit__factory } from "./factories/MedicalRecordAudit__factory";
