/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MedicalRecordAudit {
  export type AccessLogStruct = {
    accessor: AddressLike;
    recordHash: BytesLike;
    timestamp: BigNumberish;
    accessType: string;
    patientId: string;
    doctorId: string;
    isEmergency: boolean;
  };

  export type AccessLogStructOutput = [
    accessor: string,
    recordHash: string,
    timestamp: bigint,
    accessType: string,
    patientId: string,
    doctorId: string,
    isEmergency: boolean
  ] & {
    accessor: string;
    recordHash: string;
    timestamp: bigint;
    accessType: string;
    patientId: string;
    doctorId: string;
    isEmergency: boolean;
  };

  export type ConsentLogStruct = {
    patient: AddressLike;
    doctor: AddressLike;
    grantedAt: BigNumberish;
    expiresAt: BigNumberish;
    isActive: boolean;
    consentType: string;
  };

  export type ConsentLogStructOutput = [
    patient: string,
    doctor: string,
    grantedAt: bigint,
    expiresAt: bigint,
    isActive: boolean,
    consentType: string
  ] & {
    patient: string;
    doctor: string;
    grantedAt: bigint;
    expiresAt: bigint;
    isActive: boolean;
    consentType: string;
  };
}

export interface MedicalRecordAuditInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeUser"
      | "authorizedUsers"
      | "consents"
      | "getAccessCount"
      | "getAccessLogs"
      | "getConsent"
      | "getStats"
      | "grantConsent"
      | "isConsentValid"
      | "logAccess"
      | "owner"
      | "recordAccess"
      | "revokeConsent"
      | "revokeUser"
      | "totalAccesses"
      | "totalConsents"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AccessLogged" | "ConsentGranted" | "ConsentRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "consents", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAccessCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessLogs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConsent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "grantConsent",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isConsentValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logAccess",
    values: [BytesLike, BytesLike, string, string, string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordAccess",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConsent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAccesses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalConsents",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "consents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccessCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConsent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isConsentValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAccesses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalConsents",
    data: BytesLike
  ): Result;
}

export namespace AccessLoggedEvent {
  export type InputTuple = [
    recordId: BytesLike,
    accessor: AddressLike,
    timestamp: BigNumberish,
    accessType: string,
    isEmergency: boolean
  ];
  export type OutputTuple = [
    recordId: string,
    accessor: string,
    timestamp: bigint,
    accessType: string,
    isEmergency: boolean
  ];
  export interface OutputObject {
    recordId: string;
    accessor: string;
    timestamp: bigint;
    accessType: string;
    isEmergency: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentGrantedEvent {
  export type InputTuple = [
    consentId: BytesLike,
    patient: AddressLike,
    doctor: AddressLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    consentId: string,
    patient: string,
    doctor: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    consentId: string;
    patient: string;
    doctor: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentRevokedEvent {
  export type InputTuple = [
    consentId: BytesLike,
    patient: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    consentId: string,
    patient: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    consentId: string;
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedicalRecordAudit extends BaseContract {
  connect(runner?: ContractRunner | null): MedicalRecordAudit;
  waitForDeployment(): Promise<this>;

  interface: MedicalRecordAuditInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeUser: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  authorizedUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  consents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean, string] & {
        patient: string;
        doctor: string;
        grantedAt: bigint;
        expiresAt: bigint;
        isActive: boolean;
        consentType: string;
      }
    ],
    "view"
  >;

  getAccessCount: TypedContractMethod<[recordId: BytesLike], [bigint], "view">;

  getAccessLogs: TypedContractMethod<
    [recordId: BytesLike],
    [MedicalRecordAudit.AccessLogStructOutput[]],
    "view"
  >;

  getConsent: TypedContractMethod<
    [consentId: BytesLike],
    [MedicalRecordAudit.ConsentLogStructOutput],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [[bigint, bigint] & { accesses: bigint; consentsCount: bigint }],
    "view"
  >;

  grantConsent: TypedContractMethod<
    [
      consentId: BytesLike,
      patient: AddressLike,
      doctor: AddressLike,
      duration: BigNumberish,
      consentType: string
    ],
    [void],
    "nonpayable"
  >;

  isConsentValid: TypedContractMethod<
    [consentId: BytesLike],
    [boolean],
    "view"
  >;

  logAccess: TypedContractMethod<
    [
      recordId: BytesLike,
      recordHash: BytesLike,
      accessType: string,
      patientId: string,
      doctorId: string,
      isEmergency: boolean
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordAccess: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, string, string, string, boolean] & {
        accessor: string;
        recordHash: string;
        timestamp: bigint;
        accessType: string;
        patientId: string;
        doctorId: string;
        isEmergency: boolean;
      }
    ],
    "view"
  >;

  revokeConsent: TypedContractMethod<
    [consentId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeUser: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  totalAccesses: TypedContractMethod<[], [bigint], "view">;

  totalConsents: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeUser"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "consents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, boolean, string] & {
        patient: string;
        doctor: string;
        grantedAt: bigint;
        expiresAt: bigint;
        isActive: boolean;
        consentType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccessCount"
  ): TypedContractMethod<[recordId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAccessLogs"
  ): TypedContractMethod<
    [recordId: BytesLike],
    [MedicalRecordAudit.AccessLogStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConsent"
  ): TypedContractMethod<
    [consentId: BytesLike],
    [MedicalRecordAudit.ConsentLogStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { accesses: bigint; consentsCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantConsent"
  ): TypedContractMethod<
    [
      consentId: BytesLike,
      patient: AddressLike,
      doctor: AddressLike,
      duration: BigNumberish,
      consentType: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isConsentValid"
  ): TypedContractMethod<[consentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "logAccess"
  ): TypedContractMethod<
    [
      recordId: BytesLike,
      recordHash: BytesLike,
      accessType: string,
      patientId: string,
      doctorId: string,
      isEmergency: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordAccess"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, string, string, string, boolean] & {
        accessor: string;
        recordHash: string;
        timestamp: bigint;
        accessType: string;
        patientId: string;
        doctorId: string;
        isEmergency: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeConsent"
  ): TypedContractMethod<[consentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeUser"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAccesses"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalConsents"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AccessLogged"
  ): TypedContractEvent<
    AccessLoggedEvent.InputTuple,
    AccessLoggedEvent.OutputTuple,
    AccessLoggedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentGranted"
  ): TypedContractEvent<
    ConsentGrantedEvent.InputTuple,
    ConsentGrantedEvent.OutputTuple,
    ConsentGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentRevoked"
  ): TypedContractEvent<
    ConsentRevokedEvent.InputTuple,
    ConsentRevokedEvent.OutputTuple,
    ConsentRevokedEvent.OutputObject
  >;

  filters: {
    "AccessLogged(bytes32,address,uint256,string,bool)": TypedContractEvent<
      AccessLoggedEvent.InputTuple,
      AccessLoggedEvent.OutputTuple,
      AccessLoggedEvent.OutputObject
    >;
    AccessLogged: TypedContractEvent<
      AccessLoggedEvent.InputTuple,
      AccessLoggedEvent.OutputTuple,
      AccessLoggedEvent.OutputObject
    >;

    "ConsentGranted(bytes32,address,address,uint256)": TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;
    ConsentGranted: TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;

    "ConsentRevoked(bytes32,address,uint256)": TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
    ConsentRevoked: TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
  };
}
